### ISSUE TITLE
BGRU error

### ISSUE THREAD

**Issue by TangXing** [SeanNaren/CTCNetworkClient#11]
when i change BGRU to GRU an new errror appear：

 [==================== 948/948 ================>]  Tot: 13s848ms | Step: 14ms  
Training Epoch: 1
lua: /home/q/xingxing.tang/torch/install/share/lua/5.1/nn/Container.lua:67: 
In 12 module of nn.Sequential:
/home/q/xingxing.tang/torch/install/share/lua/5.1/torch/Tensor.lua:462: Wrong size for view. Input size: 22x11x400. Output size: 242x800
stack traceback:
        [C]: in function 'error'
        /home//torch/install/share/lua/5.1/torch/Tensor.lua:462: in function 'view'
        /home/g/torch/install/share/lua/5.1/ctchelpers/Linear3D.lua:70: in function </home/g/torch/install/share/lua/5.1/ctchelpers/Linear3D.lua:40>
        (tail call): ?
        [C]: in function 'xpcall'
        /home/g/torch/install/share/lua/5.1/nn/Container.lua:58: in function 'rethrowErrors'
        /homng/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function </home/q/xg/torch/install/share/lua/5.1/nn/Sequential.lua:41>
        (tail call): ?
        ./Network.lua:65: in function 'opfunc'
        /home/q/xng/torch/install/share/lua/5.1/optim/sgd.lua:44: in function 'sgd'
        ./Network.lua:81: in function 'trainNetwork'
        AN4CTCTrain.lua:45: in main chunk
        [C]: ?

WARNING: If you see a stack trace below, it doesn't point to the place where this error occured. Please use only the one above.
stack traceback:

```
    [C]: ?
```

**Comment by SeanNaren** [comment]
So what I think you've done is switched from BGRU to GRU (no bidirectional) correct? If so a standard GRU from cuDNN will output `seqLength x batch x outputSize` whereas a bidirectional would give `seqLength x batch x outputSize * 2`. Try setting the inputDims of Linear3D and the normalization layer to 200. 

EDIT: seems you managed to solve your problem :P
