### ISSUE TITLE
how to find  phoneme recognition rate from this code ?

### ISSUE THREAD

**Issue by slbinilkumar** [SeanNaren/CTCNetworkClient#14]
Hai,
Thanks for sharing this code , i want the phoneme recognition error rate from this code ,So were to modify in this code to get phoneme recognition error rate
Next in this code I had not found any were using language models but it is in etc folder of an4 dataset.
One more thing i am doing experiments with this, is it possible to modify the spectrogram or I can directly input spectrogram to this code [generated from Matlab ]

Regards
---Binil---

**Comment by SeanNaren** [comment]
So when it comes to phoneme error rate I haven't made any modifications to generate phonemes but that may come in the future. That would require altering the way the labels are created and altering the outputs from the neural net. 

You can modify the input params (everything is found in AudioData). I use a library written by [soumith](https://github.com/soumith/lua---audio) which provides a simple interface, may be good to check it out!

**Comment by SeanNaren** [comment]
I'll close this for now, but let me know if you make any good progress :)

**Comment by slbinilkumar** [comment]
sure i will update you ,if there any progress.

I am doing some experiments with your code to get better accuracy ,For that
i want to what is exactly the output of each frames in spectrogram ie it is
giving word or its character labels [ ie the output of RNN ]

I am doing pre processing the wav files weter it gives a better output or
not.

For the AN4 data base i had got around 49 and 43 accuracy without spell
checker and with spell checker

Any ways thank you for the code U had shared. I am doing my PG in AMRITA
university in coimbathore india.

https://www.*amrita*.edu/

Regards
---Binil---

**Comment by SeanNaren** [comment]
Hey! Check [this](https://github.com/SeanNaren/CTCSpeechRecognition/issues/18) out, I think you would like this :)

**Comment by slbinilkumar** [comment]
thank you very much .
