### ISSUE TITLE
To run on small size GPU memory

### ISSUE THREAD

**Issue by boleamol** [SeanNaren/CTCNetworkClient#16]
I am using Quadro k420 GPU which is having 192 cores and 1024MB memory. I already run old code but faced [out of memory issue](https://github.com/SeanNaren/CTCSpeechRecognition/issues/4) also I discussed with you regarding that. Have you modified that code for small GPU memory?

**Comment by SeanNaren** [comment]
Hey, I'll hopefully get time this week to pull some changes that allow you to set a maximum batch size. Reducing this should allow smaller memory however, I warn you that a smaller batch size will take considerably longer to train the network!

**Comment by boleamol** [comment]
Its ok, but we want to do experiment on that ....

**Comment by SeanNaren** [comment]
Sure thats understandable, give me time to add the max batch size feature (which should allow you to run training).

**Comment by SeanNaren** [comment]
I've added the feature as per said here! #20
