### ISSUE TITLE
Getting verypoor accuracy in cmu artic database

### ISSUE THREAD

**Issue by slbinilkumar** [SeanNaren/CTCNetworkClient#17]
Hai,
I had trained with cmu artic database and i am getting a very low accuracy in that .The result obtained in that is given below
 [==================== 439/439 ================>]  Tot: 19s426ms | Step: 45ms  
Without Spellcheck WER : 97.05 percent
 [==================== 439/439 ================>]  Tot: 2m8s | Step: 321ms  
With context based Spellcheck WER : 96.51 percent
So to improve the result is it possible to modify the learning parameters ?.
and i had a doubt what is the use of lexicon dictionary and language model ?

**Comment by SeanNaren** [comment]
I can't be of much use here I'm afraid because I haven't really looked into the dataset. How low is your accuracy in training and what does your loss graph look?

**Comment by slbinilkumar** [comment]
I had to look at the code once more ,is it any problem with my training
data ,The accuracy i had got is very poor getting an error rate at 97 % .I
had changed the learning rate parameter now it is getting an improvement of
10 %. Once i will go through the code and look at any fault in my side i
will get  back to you.
