### ISSUE TITLE
Training using AN4 phoneme dataset

### ISSUE THREAD

**Issue by SeanNaren** [SeanNaren/CTCNetworkClient#18]
@CCorfield was incredibly nice enough to modify the current code to now support phonemes (as well as clean the hell out of the code, will manually shift refactors into the main branch). Check it out [here](https://github.com/SeanNaren/CTCSpeechRecognition/tree/AN4Phoneme). Here is a graph showing the phoneme error rate as well as the training loss over time:

![alt text](http://i.imgur.com/eef8Ru9.png"Training graph")
Again thanks so much @CCorfield and I'll work on porting a large chunk of it over to master.

**Comment by slbinilkumar** [comment]
Thank you very much .
