### ISSUE TITLE
Error: [read_audio] Unknown length at /tmp/luarocks_audio-0.1-0-5658/lua---audio/generic/sox.c:45

### ISSUE THREAD

**Issue by Sherriiie** [SeanNaren/CTCNetworkClient#19]
I get an error when I run  the file either AN4CTCTest or AN4CTCTrain. The error details follow: 

`lua AN4CTCTest.lua
lua: ...e/sherrie/torch/install/share/lua/5.1/audio/init.lua:56: [read_audio] Unknown length at /tmp/luarocks_audio-0.1-0-5658/lua---audio/generic/sox.c:45
stack traceback:
    [C]: in function 'load'
    ...e/sherrie/torch/install/share/lua/5.1/audio/init.lua:56: in function 'load'
    ./AudioData.lua:105: in function 'an4Dataset'
    ./AudioData.lua:67: in function 'retrieveAN4TestDataSet'
    AN4CTCTest.lua:112: in main chunk
    [C]: ?
`

Could you help me?

**Comment by SeanNaren** [comment]
Hey sorry for the late reply, could you pull the master branch and see if you have the same issue? 

I assume you've ran these commands? What OS are you on?

```
sudo apt-get install libfftw3-dev
sudo apt-get install sox libsox-dev libsox-fmt-all
luarocks install https://raw.githubusercontent.com/soumith/lua---audio/master/audio-0.1-0.rockspec
```

**Comment by Sherriiie** [comment]
I am on Ubuntu 14.04 and have installed all those packages using commands. I downloaded the master branch again, and the previous error disappears. However, it says that
`lua: ./Network.lua:1: module 'optim' not found:
    no field package.preload['optim']
    no file './optim.lua'
    no file '/usr/local/share/lua/5.1/optim.lua'
    no file '/usr/local/share/lua/5.1/optim/init.lua'
    no file '/usr/local/lib/lua/5.1/optim.lua'
    no file '/usr/local/lib/lua/5.1/optim/init.lua'
    no file '/usr/share/lua/5.1/optim.lua'
    no file '/usr/share/lua/5.1/optim/init.lua'
    no file './optim.so'
    no file '/usr/local/lib/lua/5.1/optim.so'
    no file '/usr/lib/x86_64-linux-gnu/lua/5.1/optim.so'
    no file '/usr/lib/lua/5.1/optim.so'
    no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
    [C]: in function 'require'
    ./Network.lua:1: in main chunk
    [C]: in function 'require'
    ./AN4CTCTest.lua:4: in main chunk
    [C]: ?`

Actually, I have installed the optim package. The installing process is as follows:

`Install the project...
-- Install configuration: "Release"
-- Installing: /home/sherrie/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/checkgrad.lua
-- Installing: /home/sherrie/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/adagrad.lua
-- Installing: /home/sherrie/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/adadelta.lua
-- Installing: /home/sherrie/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/polyinterp.lua
-- Installing: /home/sherrie/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/rmsprop.lua
-- Installing: /home/sherrie/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/lswolfe.lua
-- Installing: /home/sherrie/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/nag.lua
-- Installing: /home/sherrie/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/adam.lua
-- Installing: /home/sherrie/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/rprop.lua
-- Installing: /home/sherrie/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/init.lua
-- Installing: /home/sherrie/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/cg.lua
-- Installing: /home/sherrie/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/sgd.lua
-- Installing: /home/sherrie/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/fista.lua
-- Installing: /home/sherrie/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/adamax.lua
-- Installing: /home/sherrie/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/asgd.lua
-- Installing: /home/sherrie/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/lbfgs.lua
-- Installing: /home/sherrie/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/Logger.lua
-- Installing: /home/sherrie/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/ConfusionMatrix.lua
-- Installing: /home/sherrie/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/cmaes.lua
Updating manifest for /home/sherrie/torch/install/lib/luarocks/rocks
optim 1.0.5-0 is now built and installed in /home/sherrie/torch/install/ (license: BSD)
`

**Comment by Sherriiie** [comment]
Sorry for my  new coming to lua. Thanks for you answering.

**Comment by Sherriiie** [comment]
`-- Installing: /home/sherrie/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/init.lua
`
The init.lua has been installed, but i can't find it in my system. How did it happen?

**Comment by Sherriiie** [comment]
I use `th` for torch interpreter, i.e. `th AN4CTCTrain.lua`, and the errors disappeared. Cheers.
