### ISSUE TITLE
training error in Training using AN4 phoneme  with artic data 

### ISSUE THREAD

**Issue by slbinilkumar** [SeanNaren/CTCNetworkClient#20]
lua AN4CTCTrain.lua  [==================== 1000/1000 ==============>]  Tot: 10s819ms | Step: 10ms  
 [==================== 131/131 ================>]  Tot: 1s417ms | Step: 10ms  
Training Epoch: 1
**\* Error in `lua': realloc(): invalid next size: 0x00000001408cc890 ***73ms  
Aborted (core dumped)

**Comment by slbinilkumar** [comment]
for the first iteration i am getting around [==================== 5/319 ==================>] 
file in a batch
how to reduce this batch file is this the problem?

**Comment by SeanNaren** [comment]
Sorry for the late reply, I've added a variable to the AN4CTCTrain script called maxSizeBatch. Setting this to 1 will make each batch 1 and hopefully let you train your model, just pull the latest master :)

**Comment by slbinilkumar** [comment]
yes now it is working,

Thank you
