### ISSUE TITLE
Data Loading Model Out of Memery

### ISSUE THREAD

**Issue by TangXing** [SeanNaren/CTCNetworkClient#22]
If i training use my own data,data loading out the memery of my michine,Can you change the  data loading model like this code https://github.com/soumith/imagenet-multiGPU.torch

**Comment by SeanNaren** [comment]
The pull request hasn't been completed yet and is still being worked on. @willfrey has notified me of the memory issue and has given me of a solution that will be implemented as soon as I can!

On the topic of using the same format as Soumith's imagenet dataloader, it is a very different dataset. The devs on the PR did a great job with handling the challenges of loading audio data and I'll be fully supporting their LMDB version!
