### ISSUE TITLE
Model file saved error 

### ISSUE THREAD

**Issue by TangXing** [SeanNaren/CTCNetworkClient#24]
hi the model  is  1.3G, 
1.3G May 31 10:37 model_epoch_1_20160531_103551_CTCNetwork.t7

**Comment by SeanNaren** [comment]
I'll modify the main branch to add a feature to save the model through training (off by default).

**Comment by SeanNaren** [comment]
The latest commit added the above feature [here](https://github.com/SeanNaren/CTCSpeechRecognition/commit/1573dc86f7d50e90275451b486386a551600c269). Hopefully this solves your issue (the model is always going to be large with this many params!).
