### ISSUE TITLE
Cpu mode doesn't work 

### ISSUE THREAD

**Issue by cricket1** [SeanNaren/CTCNetworkClient#28]
Just the change  nGPU = -1 in AN4CTCTrain.lua   doesnt work .There was NetworkCPU.lua before .Is that deprecated

**Comment by SeanNaren** [comment]
Hey, I've tried to clean things up a bit and pushed a large update to the code. Would be great if you could have a look now, I'll try to investigate further ASAP.

**Comment by cricket1** [comment]
@SeanNaren   thnks for the changes .With your changes and few code deletions I got the cpu mode to work .
Here are the code deletions 
- AN4CTCTrain.lua-cutorch.manualSeedAll(seed)
- Network.lua-cutorch.synchronize()
- UtilsMultiGPU.lua -require 'cunn'

-WEREvaluator.lua-require 'cutorch'

**Comment by SeanNaren** [comment]
Thanks, will add those changes!

**Comment by cricket1** [comment]
Also one other small change in prepare_an4/prepare.sh

chmod u+rx ./ConvertAN4ToWav.sh ./gen_index.sh   has to be changed to

chmod u+rx ./ConvertAN4ToWav.sh ./generateIndices.sh

**Comment by SeanNaren** [comment]
Added the changes you described, would be great if you could pull and have a look :)

**Comment by cricket1** [comment]
No issues seen :+1:
