### ISSUE TITLE
To use the code using CPU

### ISSUE THREAD

**Issue by patelrajnath** [SeanNaren/CTCNetworkClient#3]
Hi,

Thanks for sharing the code.

Is it possible to use the same using CPU instead of GPU (just for testing)? If so, what are the changes we need to do and in what files. Any help is appreciated.

**Comment by SeanNaren** [comment]
I've added a file [here](https://github.com/SeanNaren/CTCSpeechRecognition/blob/master/NetworkCPU.lua)  on the main branch that replaces the Network.lua class and will run on the CPU.
In the AN4CTCTrain, just change the require 'Network' to require 'NetworkCPU' to use it. 

Hopefully this helps, let me know if you can run it (Not sure how fast it is on CPU).

**Comment by patelrajnath** [comment]
Thanks for quick response. We have made the changes as suggested, but its giving error related to 'cutorch', which is required in "AudioData.lua". And I guess "cutorch" does require CUDA, which is not installed in our case. Any suggestion/correction?

**Comment by SeanNaren** [comment]
Woops I just removed the call now based on what you said, try pulling again! Thanks!

**Comment by patelrajnath** [comment]
Hi, CUDA has been used in NetworkCPU.lua. Please have a look for the same.

**Comment by SeanNaren** [comment]
Ah sorry removed the conversion of the criterion to CUDA, thanks.

**Comment by boleamol** [comment]
Still we are getting the error: "**lua: ./NetworkCPU.lua:82: attempt to call field 'CTCCriterion' (a nil value)**", kindly suggest.

**Comment by SeanNaren** [comment]
Seems like their was some package confusion, try pulling again (I required the nnx library in both Network class). This should hopefully fix everything!

**Comment by boleamol** [comment]
Again we are getting same error: "**lua: ./NetworkCPU.lua:83: attempt to call field 'CTCCriterion' (a nil value)
stack traceback:**
" , Please suggest ...

**Comment by SeanNaren** [comment]
Have you installed the nnx packages via luarocks install nnx?

**Comment by boleamol** [comment]
Yes, Its installed and I checked by using "luarocks list"

**Comment by SeanNaren** [comment]
When was the last time you installed it? Try updating it by running the same command? The criterion was only pushed in a few days ago!

**Comment by boleamol** [comment]
I installed just before running CTC (I followed steps which is mentioned by you in Readme.md file). But now I am running it on CPU and I made changes in AN4CTCTrain.lua which is mentioned by you

**Comment by SeanNaren** [comment]
Just want to confirm, is the problem still happening or has it been fixed?

**Comment by boleamol** [comment]
Now it is in running state.... If any query occure then I will ask you.. Thank you for your support...

**Comment by SeanNaren** [comment]
Great! That should hopefully fix this issue, if you run into anything else feel free to open another issue.

**Comment by cricket1** [comment]
@SeanNaren  no plans to support the CPU mode anymore ?
