### ISSUE TITLE
ctchelpers missing

### ISSUE THREAD

**Issue by graphific** [SeanNaren/CTCNetworkClient#30]
Hey Sean,
it seems your ctchelpers repo is missing which is needed to run the deepspeech net, mainly:

> ctchelpers/Linear3D.lua
> ctchelpers/CombineDimensions.lua

**Comment by SeanNaren** [comment]
Hey! Is this for an older branch of the code? If there is a reason you are using this older branch, I can write up an alternative (as there are better ways to handle combine dimension and Linear3D).

**Comment by graphific** [comment]
yes its the code checked in at the AN4Phoneme branch.

**Comment by SeanNaren** [comment]
Will modify the phoneme branch to not require this, thanks!

**Comment by walkers-mv** [comment]
I was working on a similar problem. I have a simple version of the changes necessary for going from the character based model on master to a phoneme model on this branch in my fork:
https://github.com/walkers-mv/CTCSpeechRecognition/tree/new_an4_phoneme

**Comment by SeanNaren** [comment]
@walkers-mv that looks awesome! Would be cool if you could open a PR for it :) Getting the changes into the old branch has been a bit of a task...

**Comment by SeanNaren** [comment]
@graphific sorry for such a delayed response time, but it should be fixed now, let me know if you run into any issues!

EDIT: there are some convergence issues, will handle them ASAP. It would be nice to start adding phoneme support to the main branch though :)
