### ISSUE TITLE
lmdb Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by graphific** [SeanNaren/CTCNetworkClient#32]
At Utility.lua is there a reason to use the [tnx.abort()](https://github.com/SeanNaren/CTCSpeechRecognition/blob/master/Utils.lua#L53) as it logically will throw a `Segmentation fault (core dumped)` when kept in place and used to create the lmdb's:

```
xn:commit()
--> txn:abort()
db:close()
```

**Comment by SeanNaren** [comment]
I'll have a look, it doesn't seem necessary but will make sure thanks!
