### ISSUE TITLE
Why not using nn.SeqBRNN ?

### ISSUE THREAD

**Issue by Mohamed-Elbially** [SeanNaren/CTCNetworkClient#33]
This is not an issue actually, but I was asking why not using nn.SeqBRNN in building the deepspeech model instead of using MaskRNN and ReverseMaskRNN ?. Thank you.

**Comment by SeanNaren** [comment]
Hey, this was when we were zeroing out the padded areas of the RNN using MaskRNN and ReverseMaskRNN. In the latest branch this has been removed (more in tune with what Baidu did, which was just use the real sizes in the cost calculations).

Hope that answers your question!

**Comment by Mohamed-Elbially** [comment]
Thank you Sean, yes I noticed you replaced it in the branch to be BLSTM. Is there a reason not to merge it with the master yet ?

**Comment by SeanNaren** [comment]
It's actually a Bidirectional RNNReLU layer which is what baidu use internally. That is what's currently on the main branch! I still haven't figured out how to do BLSTM with batch norm correctly using cudnn sadly :(

**Comment by Mohamed-Elbially** [comment]
Thank you Sean, I'll search for it and comeback to you if I found anything
