### ISSUE TITLE
How to choose convolutional layers parameters for different spectrogram sizes 

### ISSUE THREAD

**Issue by Mohamed-Elbially** [SeanNaren/CTCNetworkClient#35]
Hey Sean, I was asking how the parameters of the convolutional layers related to the size of the spectrogram. I want to change the spectrogram parameters to be : 
windowSize = 100
stride = 50
how to choose the parameters of the convolutional layers to work on spectrogram of this size?.

Thank you.

**Comment by SeanNaren** [comment]
I'm just gathering a good answer for this, give me some time :)

**Comment by SeanNaren** [comment]
@Mohamed-Elbially sorry for the extremely late reply, and sadly I couldn't come back with a very informative response. Most of the time if I wanted to change the windowSize and stride I would change them and then check what the output size from the convolutional layers were by putting this layer after the convolutional layers:

``` lua
require 'rnn'
nn.PrintSize("Convolutional sizes")
```

Some words from my friend Will:
- He can alter the convolution kernel sizes according to a similar ratio of your current kernel sizes to the input sizes you are using.
- He has to do the math to figure out how to get the right output size such as 
  `floor((size - kW + 2 * padW) / dW)` For both width W and height H If he wants to use different
  sized spectrograms and keep the convolutional kernels the same.

The spectrogram stride/window size are similar to values used by Baidu (the ones found in this repo as well).

**Comment by Mohamed-Elbially** [comment]
@SeanNaren Thanks a lot,I started to work with the equation floor((width  + 2*padW - kW) / dW +1) from torch documentation. but nn.PrintSize works like charm :) . Just small typo from your reply 

``` Lua
require 'dpnn'      --not rnn 
nn.PrintSize("Convolutional sizes")
```

Thank you Sean
