### ISSUE TITLE
Module 'BatchRNNReLU' not found

### ISSUE THREAD

**Issue by shantanudev** [SeanNaren/CTCNetworkClient#36]
Hi,

I was able to successfully train the model with the an4 data. However, after trying to run the testing script, I ran into module the error below: 
'BatchRNNReLU' not found:No LuaRocks module found for BatchRNNReLU no field package.preload['BatchRNNReLU]

I clearly see the module within the folder. I was hoping you could help me out.

Thanks

**Comment by SeanNaren** [comment]
Hey, will sort this out soon just some dependencies need to be added.

**Comment by SeanNaren** [comment]
Done! Should be fixed for both branches, could you let me know if the error is gone?

**Comment by shantanudev** [comment]
Hey, 
Thanks works now! I appreciate the detailed guide and quick response.
