### ISSUE TITLE
AN4 decoding result

### ISSUE THREAD

**Issue by lifeiteng** [SeanNaren/CTCNetworkClient#38]
Hi,
Does the model get reasonable WER？It's better putting decoding WER info into a file(e.g RESULTS) and commit it.

Recently, I warp cudnn-RNN and warp-ctc using C++ language,  but the training process is abnormal.
I write test code for `RecurrentForwardTraining`, the output of cudnn LSTM is different with the result of the formula(has typo) in [Step 1: Optimizing a Single Iteration](https://devblogs.nvidia.com/parallelforall/optimizing-recurrent-neural-networks-cudnn-5/), block here. So I wanna know the progress in here (there is error loading torch when I run the code, have not time to solve it.)

Best,
Feiteng

**Comment by SeanNaren** [comment]
Hey! I'll write in the README the current state of the WER/CER.

**Comment by lifeiteng** [comment]
I switch to other RNN implementation, training is normal(about three epoch):

```
Iter Predict-Accuracy
50  0.589026
100  0.675046
150  0.718223
200  0.737348
250  0.750125
300  0.774845
```

I'll re-check my usage of cudnn-RNN.

Best,
Feiteng

**Comment by SeanNaren** [comment]
Added in #43, check README
