### ISSUE TITLE
More Time taken for an epoch in multi-gpu case 

### ISSUE THREAD

**Issue by cricket1** [SeanNaren/CTCNetworkClient#40]
I am using ec2 instance g2.8xlarge that has 4 gpu's .
I have changed nGPU = 4 in AN4CTCTrain.lua .

I see that 
- nGPU =4 
  epoch takes on an avg 55 s
- nGPU =1 
  epoch takes on an avg 48 s

Am I doing something wrong .

**Comment by SeanNaren** [comment]
How about larger batch sizes? I feel that is where multi-gpu support will become useful!

**Comment by seed93** [comment]
1. larger batch size will be more efficient.
2. use input of same seqlength or in random order.

**Comment by cricket1** [comment]
Oh it works ....thnks for the suggestions
