### ISSUE TITLE
"nan" value of average loss when training using LibriSpeech corpus

### ISSUE THREAD

**Issue by zssloth** [SeanNaren/CTCNetworkClient#41]
Hi~@SeanNaren, I just get a "nan" value of average loss when training using LibriSpeech corpus: 
![screenshot from 2016-07-29 12 26 45](https://cloud.githubusercontent.com/assets/11425143/17237759/cb93c192-5587-11e6-94fe-fb52dbc84749.png)
I think the problem comes from indexer:nxt_inds() in Loader.lua. When:
`self.lmdb_size = self.cnt + self.batch_size - 1` 
then:
    `self.cnt = self.batch_size - (self.lmdb_size - self.cnt) = 1`  
the following code will cause unexpected issues since  `self.cnt - 1 = 0`:
   `for i = 1, self.cnt - 1 do`
    `table.insert(inds, i)`
    `end`
It's that right?

**Comment by SeanNaren** [comment]
LMDB should throw out an error if you try to index something that doesn't have a pair in the database for, so I'm not entirely sure that's the issue. 

I'll be implementing grad norm into the feval function which may help handle the explosion in gradients that I think is occuring, however this may be only one step in the fix.

**Comment by zssloth** [comment]
Thank you. I think you are right since fixing the code I mentioned above prove to be useless, the problem still occurs after a certain amount of epochs.
