### ISSUE TITLE
Issue with nn.bottle dependency

### ISSUE THREAD

**Issue by shantanudev** [SeanNaren/CTCNetworkClient#45]
Hi Sean,

I am trying to refactor my code into your updated changes. However, I am facing an issue with the Bottle being a 'nil value'. Below is the log:
 ./DeepSpeechModel.lua:36: attempt to call field 'Bottle' (a nil value)
stack traceback:
    ./DeepSpeechModel.lua:36: in function <./DeepSpeechModel.lua:14>
    ./Network.lua:73: in function 'prepSpeechModel'
    ./Network.lua:57: in function 'init'
    Libri_Train.lua:39: in main chunk

**Comment by SeanNaren** [comment]
Bottle was added in the latest nn update, would suggest doing a `luarocks install torch` and `luarocks install nn`

**Comment by shantanudev** [comment]
Ah, I only updated nn library. I didn't update torch. Thanks!
