### ISSUE TITLE
Create pre-trained model on Librispeech

### ISSUE THREAD

**Issue by SeanNaren** [SeanNaren/CTCNetworkClient#49]
There has been a lot of attempts to get the model trained on Librispeech 1k hours of training data so providing a trained model I think would be very beneficial (as well as the steps to replicate).
- [x] Prepare dataset on file system
- [x] Create LMDB and make modifications to support this
- [x] Train till convergence
- [x] Add model to repo and document

Stretch goal:
- [x] Allow loading of previous model and training from these weights

**Comment by nfmelendez** [comment]
+1

**Comment by SeanNaren** [comment]
I've added a checklist to the main issue which I'll update as I complete tasks!

**Comment by SeanNaren** [comment]
I'm training the model now. I've modified params and will explain how I trained this model from the ground up. It doesn't strictly follow the DeepSpeech architecture mainly out of performance reasons and aiding convergence.

**Comment by iassael** [comment]
Hi @SeanNaren, are you planning to upload the model? The community thanks you!

**Comment by SeanNaren** [comment]
@iassael Sorry for the disappearance... will upload the models tomorrow and give the WER/CERs currently for them. Still plan on improving the smaller version but will get the release out!

**Comment by iassael** [comment]
@SeanNaren that's amazing. If you need any help with hosting let me know!

**Comment by SeanNaren** [comment]
[Here](https://github.com/SeanNaren/deepspeech.torch#pre-trained-networks) we are guys :) Huuuge thank you to @maciejkorzepa for giving me the LibriSpeech model!

I think we could squeeze a little bit more out of some of the models in terms of accuracies, but they are a good baseline to start from!

@iassael Thanks for the offer of hosting, Seems like github handled them alright

**Comment by ryanleary** [comment]
@SeanNaren do you have information on how you were able to make this converge?
