### ISSUE TITLE
problem with installing audio lib

### ISSUE THREAD

**Issue by fanlamda** [SeanNaren/CTCNetworkClient#61]
After I installed the first two package named fftw3-dev and sox，I used” luarocks install https://raw.githubusercontent.com/soumith/lua---audio/master/audio-0.1-0.rockspec“ , it comes error like

Scanning dependencies of target audio
[ 50%] Building C object CMakeFiles/audio.dir/audio.c.o
Linking C shared module libaudio.so
/usr/bin/ld: /usr/local/lib/libfftw3.a(mapflags.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libfftw3.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: **\* [libaudio.so] Error 1
make[1]: **\* [CMakeFiles/audio.dir/all] Error 2
make: **\* [all] Error 2

Error: Build error: Failed building.

I tried to figure this out but failed

**Comment by SeanNaren** [comment]
Which OS is this?

**Comment by fanlamda** [comment]
thanks for reply ，ubuntu

**Comment by SeanNaren** [comment]
Just to make sure did you run:

```
$ sudo apt-get install libfftw3-dev
$ sudo apt-get install sox libsox-dev libsox-fmt-all
```

**Comment by fanlamda** [comment]
yes，I did this exactly，it really confuses me......But I installed this in other computer successfully, so I used other computer to prepare the data, which is inconvenient

**Comment by SeanNaren** [comment]
I'll close this for now, if the issue comes up again feel free to open this again...
