### ISSUE TITLE
Problem with mapper

### ISSUE THREAD

**Issue by fanlamda** [SeanNaren/CTCNetworkClient#63]
I changed a few things in mapper.lua to adapt to Chinese study, but it comes error like 
/home/fanl/torch/install/share/lua/5.1/threads/threads.lua:183: [thread 1 callback] ./Mapper.lua:23: bad argument #1 to 'lower' (string expected, got nil)
stack traceback:
    [C]: in function 'lower'
    ./Mapper.lua:23: in function 'encodeString'
    ./Loader.lua:92: in function <./Loader.lua:62>

**Comment by SeanNaren** [comment]
So it seems like the line going into the mapper is nil for some odd reason, is there any way that a nil could've been inserted into the LMDB, or the label is nil?

**Comment by fanlamda** [comment]
There was a mistake in label when I dealt with the label. Now it works
