### ISSUE TITLE
Method for Loading Weights and Saving Them

### ISSUE THREAD

**Issue by nn-learner** [SeanNaren/CTCNetworkClient#64]
Hi Sean,

I was wondering if there was a way to load the weights of the model, train it on another dataset, and save the weights again. Currently, you are only able to either load or save the weights.

**Comment by SeanNaren** [comment]
Hey on the main branch you should be able to load (and save) a model after training. You do need to setup the dataset using the wiki guide [here](https://github.com/SeanNaren/deepspeech.torch/wiki/Data-Preparation). You can load a model like this:

`th Train.lua -loadModel -modelPath Path/To/Model.t7`.

Hopefully this helps!
