### ISSUE TITLE
Questions about training AN4 dataset

### ISSUE THREAD

**Issue by Yizhen-Z** [SeanNaren/CTCNetworkClient#66]
I followed the installation guide and tried to run `Train.lua` on AN4 dataset.
But the results I got was quite strange, the `Average Loss` turned out to be a huge number, while `WER` and `CER` were also larger than 100. (In my understanding, it should be a percentage number which is less than 100).
![screenshot](https://cloud.githubusercontent.com/assets/21225063/19946139/82e310aa-a119-11e6-97e8-8f64c164485e.png)

I didn't make any change on code. So I am really confused about it...

Another question is that, from the DS2 paper `CER` refers to 'Characer Error Rate' for the Mandarin system, so what is `CER` here refers to?

Thanks for any advise!

**Comment by SeanNaren** [comment]
Could you let me know what OS/GPU you are using?

**Comment by Yizhen-Z** [comment]
The OS is Ubuntu 16.04.1.
GPU is NVIDIA GTX 1080.

Thanks for reply!

**Comment by SeanNaren** [comment]
Yeah I had the same issue as you, you need to install `warp-ctc` a bit differently on pascal cards, check [here](https://github.com/baidu-research/warp-ctc/pull/48) and try installing this branch instead, and restarting training!

**Comment by Yizhen-Z** [comment]
Yes, it works now. I finally got WER = 18, and CER = 3.88 on AN4 dataset.
Thank you!
![loss](https://cloud.githubusercontent.com/assets/21225063/20063983/0f9f21da-a4d7-11e6-9194-cbb5c73c04be.png)

**Comment by SeanNaren** [comment]
Great stuff!
