### ISSUE TITLE
Trained model file download

### ISSUE THREAD

**Issue by zavalyshyn** [SeanNaren/CTCNetworkClient#70]
Hi,

I've been running the Train.lua script for days on my setup (no GPU, just CPU) and managed to move to the second epoch. 

Is there a way to download a pretrained deepspeech AN4 model from somewhere?

I'd really appreciate this. Thanks

**Comment by SeanNaren** [comment]
Hey sorry for the late response. I'll do this when I can, I plan to release two models for Librispeech and for AN4, but not entirely sure where to put it, any suggestions?

EDIT: I'll make a release and put it there

**Comment by zavalyshyn** [comment]
Hey, cool thanks.

I can store it on my Dropbox. I have 27 gigs there which I don't use.

**Comment by shantanudev** [comment]
You can also store it on my google drive if you are interested. I have unlimited space.

**Comment by nn-learner** [comment]
@SeanNaren Thank you Sean! What is the best WER% you have been able to achieve so far?

**Comment by SeanNaren** [comment]
Sorry for the disappearance, everything can be seen [here](https://github.com/SeanNaren/deepspeech.torch#pre-trained-networks)!

**Comment by SeanNaren** [comment]
I realised some people may want a CPU only model (would take forever to train on Libri, I can do this for AN4 only). I'll make a ticket for this.

**Comment by zavalyshyn** [comment]
Thank you so much for that. That's exactly my case.
