### ISSUE TITLE
Loading Weights and MultiGPU Support

### ISSUE THREAD

**Issue by nn-learner** [SeanNaren/CTCNetworkClient#72]
Whenever I load the weights, how come the model is not utilizing the other GPUs? It only loads it on 1 GPU.

**Comment by nileshnegi** [comment]
Have you tried using the -nGPU option?

**Comment by SeanNaren** [comment]
Using the `-nGPU` option should load the model onto every GPU. Let me know if this doesn't fix the problem, and we can re-open the issue.
