### ISSUE TITLE
AMD APU Support

### ISSUE THREAD

**Issue by Whytehorse** [SeanNaren/CTCNetworkClient#75]
I saw the installation notes have a lot about CUDA but not OpenCL. Does this software require an Nvidia GPU to work? Are there plans to add other GPUs like AMD?

**Comment by SeanNaren** [comment]
Hey! There is support for OpenCL for Torch but it isn't implemented in this repo. I've made modifications in the past to support opencl using [this](https://github.com/hughperkins/cltorch) repo, and it was significantly slower than CUDA.

So yes, it does require an NVIDIA GPU currently, and someone needs to give a kick up AMDs backside till they start pushing deep learning support :)
