### ISSUE TITLE
Issue with configuring training

### ISSUE THREAD

**Issue by eranfain** [SeanNaren/CTCNetworkClient#76]
Hello,
I am using Mac OS X 10.10.2 with CUDA 8.0 and cudnn V5.
When I run the following command (as part of the AN4 setup):
th MakeLMDB.lua -rootPath prepare_datasets/an4_dataset -lmdbPath prepare_datasets/an4_lmdb -windowSize 0.02 -stride 0.01 -sampleRate 16000

I get the following exception:

/Users/admin/torch/install/bin/luajit: /Users/admin/torch/install/share/lua/5.1/trepl/init.lua:389: /Users/admin/torch/install/share/lua/5.1/lmdb/ffi.lua:175: dlopen(liblmdb.dylib, 5): image not found
stack traceback:
	[C]: in function 'error'
	/Users/admin/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	MakeLMDB.lua:7: in main chunk
	[C]: in function 'dofile'
	...dmin/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x010b83bd50

Any help would be appreciated.

**Comment by suhaspillai** [comment]
Check your lmdb installation
What happens when you do 'require lmdb'  ?
Just go step by step
get the audio
load the audio
calculate spectrogram 
and then create lmdb data just for that sample.

**Comment by eranfain** [comment]
Ok.
The problem is solved.
I probably had something wrong with the lmdb installation.

Thank you!

**Comment by SeanNaren** [comment]
Thanks @suhaspillai for your help and glad your problem is fixed @eranfain
