### ISSUE TITLE
AN4 Setup problems

### ISSUE THREAD

**Issue by joseph-osborne** [SeanNaren/CTCNetworkClient#89]
So when I try to run "th FormatAN4.lua -rootPath an4 -newPath an4_dataset # puts an4 into the correct format under folder 'dataset' " I get the following:

this is the command: th FormatAN4.lua /media/jpldev/E/RNN_tests/deepspeech/prepare_datasets an4 /media/jpldev/E/RNN_tests/deepspeech/prepare_datasets an4_dataset

this is the output I get: invalid argument: /media/jpldev/E/RNN_tests/deepspeech/prepare_datasets	
Usage: [options]
  -rootPath       Path to the an4 root [an4]
  -newPath        Path to the new data path [an4_dataset]
  -audioExtension The extension of the audio files (wav/mp3/sph/etc) [sph]
  -move           Moves the files over rather than copies, used to save space [false]

I don't know what I could be doing wrong.  Any help would be appreciated. Thank you!

**Comment by SeanNaren** [comment]
you need to include the flags like below:

```
th FormatAN4.lua -rootPath /media/jpldev/E/RNN_tests/deepspeech/prepare_datasets/an4 -newPath /media/jpldev/E/RNN_tests/deepspeech/prepare_datasets/an4_dataset
```

**Comment by joseph-osborne** [comment]
Thank you for the help!  I have another question though.  When I try " th MakeLMBD.lua -rootPath /media/jpldev/E/RNN_tests/deepspeech/prepare_datasets/an4_dataset -lmdbPath /media/jpldev/E/RNN_tests/deepspeech/prepare_datasets/an4_lmdb -windowSize 0.02 -stride 0.01 -sampleRate 16000" it gives me this error:

/home/jpldev/torch/install/bin/luajit: cannot open MakeLMBD.lua: No such file or directory
stack traceback:
	[C]: in function 'dofile'
	...ldev/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50

Is there a certain file I need to update so it can find MakeLMBD.lua? I've tried it several different directories along the path to MakeLMBD.lua and it gives the same error for all of them.

**Comment by suhaspillai** [comment]
Its not able to find MakeLMDB.lua.....check if its in your directory before running th MakeLMDB.lua

**Comment by SeanNaren** [comment]
@j0sborne its `MakeLMDB.lua` not `MakeLMBD.lua`
