### ISSUE TITLE
Error Sample Rate 8khz

### ISSUE THREAD

**Issue by stephenvxx** [SeanNaren/CTCNetworkClient#96]
I had a error : 

>  /home/datvt12/torch/install/share/lua/5.1/cudnn/init.lua:162: Error in CuDNN: CUDNN_STATUS_BAD_PARAM (cudnnGetConvolutionNdForwardOutputDim)
> stack traceback:
> 	[C]: in function 'error'
> 	/home/datvt12/torch/install/share/lua/5.1/cudnn/init.lua:162: in function 'errcheck'
> 	...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:140: in function 'createIODescriptors'
> 	...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:188: in function <...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:186>
> 	[C]: in function 'xpcall'
> 	/home/datvt12/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
> 	/home/datvt12/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function </home/datvt12/torch/install/share/lua/5.1/nn/Sequential.lua:41>
> 	[C]: in function 'xpcall'
> 	/home/datvt12/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
> 	/home/datvt12/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function </home/datvt12/torch/install/share/lua/5.1/nn/Sequential.lua:41>
> 	[C]: in function 'xpcall'
> 	.../datvt12/torch/install/share/lua/5.1/threads/threads.lua:234: in function 'callback'
> 	/home/datvt12/torch/install/share/lua/5.1/threads/queue.lua:65: in function </home/datvt12/torch/install/share/lua/5.1/threads/queue.lua:41>
> 	[C]: in function 'pcall'
> 	/home/datvt12/torch/install/share/lua/5.1/threads/queue.lua:40: in function 'dojob'
> 	[string "  local Queue = require 'threads.queue'..."]:13: in main chunk
> 
> WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
> stack traceback:
> 	[C]: in function 'error'
> 	/home/datvt12/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
> 	/home/datvt12/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function </home/datvt12/torch/install/share/lua/5.1/nn/Sequential.lua:41>
> 	[C]: in function 'xpcall'
> 	.../datvt12/torch/install/share/lua/5.1/threads/threads.lua:234: in function 'callback'
> 	/home/datvt12/torch/install/share/lua/5.1/threads/queue.lua:65: in function </home/datvt12/torch/install/share/lua/5.1/threads/queue.lua:41>
> 	[C]: in function 'pcall'
> 	/home/datvt12/torch/install/share/lua/5.1/threads/queue.lua:40: in function 'dojob'
> 	[string "  local Queue = require 'threads.queue'..."]:13: in main chunk
> stack traceback:
> 	[C]: in function 'error'
> 	.../datvt12/torch/install/share/lua/5.1/threads/threads.lua:183: in function 'dojob'
> 	.../datvt12/torch/install/share/lua/5.1/threads/threads.lua:264: in function 'synchronize'
> 	...2/torch/install/share/lua/5.1/cunn/DataParallelTable.lua:737: in function 'exec'
> 	...2/torch/install/share/lua/5.1/cunn/DataParallelTable.lua:197: in function 'forward'
> 	./Network.lua:134: in function 'opfunc'
> 	/home/datvt12/torch/install/share/lua/5.1/optim/sgd.lua:44: in function 'sgd'
> 	./Network.lua:158: in function 'trainNetwork'
> 	Train.lua:43: in main chunk
> 	[C]: in function 'dofile'
> 	...vt12/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
> 	[C]: at 0x00405ea0

In Deepspeechmodel.lua, i change rnnInputsize = 1 * 81 ( Because size output :20x1x81x13) 
Please help me ! @SeanNaren

**Comment by stephenvxx** [comment]
@AdolfVonKleist

**Comment by SeanNaren** [comment]
What dataset are you training on?

**Comment by stephenvxx** [comment]
I use my dataset (Be formatted as AN4). The firstly, i make LMDB sample rate 8000. Then i modify DeepspeechModel.lua, rnnInputsize= 1*81. I still change rnnInputSize !
 

> conv:add(nn.SpatialConvolution(1, 32, 11, 41, 2, 2))
>     conv:add(nn.SpatialBatchNormalization(32))
>     conv:add(nn.Clamp(0, 20))
>     conv:add(nn.SpatialConvolution(32, 32, 11, 21, 2, 1))
>     conv:add(nn.SpatialBatchNormalization(32))
>     conv:add(nn.Clamp(0, 20))


I dont understand this code, why nInputPlane=1, etc... I dont know to modify SpatialConvolution and rnnInputSize .

**Comment by SeanNaren** [comment]
What is the size of the shortest clip? Could you make sure its above 0.5 seconds long? Otherwise it might not be large enough to go through the convolutional layers.

**Comment by stephenvxx** [comment]
@SeanNaren I cut all my wav above 1.0 seconds, but it is not change. Is a bug of cuda r5 ?

**Comment by SeanNaren** [comment]
Any chance this could help figure it out? https://github.com/SeanNaren/deepspeech.torch/issues/62#issuecomment-255733363

**Comment by stephenvxx** [comment]
Sometimes, i cut my wav files above 1.0 seconds (5000 files). The Bug error message is on #62 and i fix it. When i use all my audio files (1 Million Files) not successfully.
